**This is a NLP problem where the task is to classify Fake News in an article. This notebook consists of various stages needed for identifying fake news such as data preprocessing, model experimentation, and evaluation of results.**

In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
from tensorflow.keras.layers import Embedding,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM,Bidirectional,GRU
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
# Reading data from csv
train = pd.read_csv("train.csv")
test  = pd.read_csv("test.csv")
train.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
test.head()

id                                              title  \
0  20800  Specter of Trump Loosens Tongues, if Not Purse...   
1  20801  Russian warships ready to strike terrorists ne...   
2  20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3  20803  Tim Tebow Will Attempt Another Comeback, This ...   
4  20804                    Keiser Report: Meme Wars (E995)   

                    author                                               text  
0         David Streitfeld  PALO ALTO, Calif.  —   After years of scorning...  
1                      NaN  Russian warships ready to strike terrorists ne...  
2            Common Dreams  Videos #NoDAPL: Native American Leaders Vow to...  
3            Daniel Victor  If at first you don’t succeed, try a different...  
4  Truth Broadcast Network  42 mins ago 1 Views 0 Comments 0 Likes 'For th...

In [4]:
# Displaying rows and columns in dataset
print("There are {} number of rows and {} number of columns for training.".format(train.shape[0],train.shape[1]))
print("There are {} number of rows and {} number of columns for testing.".format(test.shape[0],test.shape[1]))

There are 20800 number of rows and 5 number of columns for training.
There are 5200 number of rows and 4 number of columns for testing.


**Checking Null Values**

In [5]:
# Checking the null values in training data.
train.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
# Checking the null values in testing data.
test.isnull().sum()

id          0
title     122
author    503
text        7
dtype: int64

In [7]:
# Handling nan values in dataset using empty spaces
def handle_nan(train_data,test_data):
    '''Input: Data to the function containing Nan values.
       Output : Cleaned data containing no Nan values.
       Function: Cleaning Nan values.
     '''
    train = train_data.fillna(" ")
    test  = test_data.fillna(" ")
    return train,test

train,test = handle_nan(train,test)


In [8]:
# Creating a variable "merged" by merging columns "title" and "author"
train["merged"] = train["title"]+" "+train["author"]
test["merged"]  = test["title"]+" "+test["author"]

In [9]:
# Seperating Independent and dependent features
X = train.drop(columns=['label'],axis=1)
y = train['label']

In [10]:
# Creating One-Hot Representations
messages = X.copy()
messages.reset_index(inplace=True)
messages_test = test.copy()
messages_test.reset_index(inplace=True)

# Data Pre-processing
**In Data Pre-processing following steps are followed:** 
**1. Firstly, all the sequences except english characters are removed from the string.**
**2. Next, to avoid false predictions or ambiguity with upper and lowercase, all the characters in strings are converted    to lowercase.**
**3. Next, all the sentences are tokenized into words.**
**4. To facilitate fast processing, stemming is applied to the tokenized words.**
**5. Next, words are joined together and stored in the corpus.**

**Note: In this we have used "merged" column for classification task. Also, the loop inside the function runs over all the examples in the merged column.**

In [11]:
# Performing data preprocessing on column 'title'
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def perform_preprocess(data):
    '''Input: Data to be processed
       Output: Preprocessed data
    '''
    corpus = []
    for i in range(0,len(data)):
        review = re.sub('[^a-zA-Z]',' ',data['merged'][i])
        review = review.lower()
        review = review.split()
        review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
        review = ' '.join(review)
        corpus.append(review)
    return corpus
    
train_corpus = perform_preprocess(messages)
test_corpus  = perform_preprocess(messages_test)
train_corpus[1]

'flynn hillari clinton big woman campu breitbart daniel j flynn'

In [12]:
test_corpus[1]

'russian warship readi strike terrorist near aleppo'

**Below code converts the pre-processed words to one-hot vectors in the range of vocabulary size=5000. This is done to obtain numerical feature matrix**

In [13]:
# Converting to one-hot repr.
vocab_size = 5000
one_hot_train = [one_hot(word,vocab_size) for word in train_corpus]
one_hot_test  = [one_hot(word,vocab_size) for word in test_corpus]

In [14]:
one_hot_test[1]

[1121, 3418, 1703, 1472, 4878, 2130, 3816]

**Below code creates an embedding layer which applies "pre" padding to the one-hot encoded features with sentence length = 20. Padding is applied so that the length of every sequence in the dataset should be same.**

In [15]:
# Embedding Representation 
sent_length = 20
embedd_docs_train = pad_sequences(one_hot_train,padding='pre',maxlen=sent_length)
embedd_docs_test  = pad_sequences(one_hot_test,padding='pre',maxlen=sent_length)
print(embedd_docs_train)

[[   0    0    0 ... 1272 3336 2171]
 [   0    0    0 ... 2597 3078 2925]
 [   0    0    0 ... 3893   61 2492]
 ...
 [   0    0    0 ...  130 1764  451]
 [   0    0    0 ... 3981 3934 3467]
 [   0    0    0 ... 4137 3875 1294]]


In [16]:
print(embedd_docs_test)

[[   0    0    0 ... 1013 3875 1348]
 [   0    0    0 ... 4878 2130 3816]
 [   0    0    0 ... 1923 1504 2303]
 ...
 [   0    0    0 ... 1013 4014 3774]
 [   0    0    0 ... 1121 2342 1581]
 [   0    0    0 ... 1013  167 3092]]


In [17]:
# Converting Embedding repr. to array
x_final = np.array(embedd_docs_train)
y_final = np.array(y)
x_test_final = np.array(embedd_docs_test)

In [18]:
# Dimensions of prev. array repr.
x_final.shape,y_final.shape,x_test_final.shape

((20800, 20), (20800,), (5200, 20))

**Dividing the dataset into training,validation and testing data (ratio: 80/10/10) using train_test_split technique.**

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.1, random_state=42, stratify = y_final)
X_train, x_valid, Y_train, y_valid = train_test_split(x_train, y_train, test_size=0.1, random_state=42, stratify = y_train)
x_test_final = x_test_final

# Creating Models
**In this phase, several models are created and evaluated against various metrics shown using classification report.**

**1. Logistic Regresssion**

In [20]:
model_1 = LogisticRegression(max_iter=900)
model_1.fit(X_train,Y_train)
pred_1 = model_1.predict(x_test)
cr1    = classification_report(y_test,pred_1)
print(cr1)

              precision    recall  f1-score   support

           0       0.68      0.75      0.71      1039
           1       0.72      0.65      0.68      1041

    accuracy                           0.70      2080
   macro avg       0.70      0.70      0.70      2080
weighted avg       0.70      0.70      0.70      2080



**2. Naive Bayes**

In [21]:
model_2 = MultinomialNB()
model_2.fit(X_train,Y_train)
pred_2 = model_2.predict(x_test)
cr2    = classification_report(y_test,pred_2)
print(cr2)

              precision    recall  f1-score   support

           0       0.73      0.65      0.69      1039
           1       0.69      0.76      0.72      1041

    accuracy                           0.71      2080
   macro avg       0.71      0.71      0.71      2080
weighted avg       0.71      0.71      0.71      2080



**3. Decision Trees**

In [22]:
model_3 = DecisionTreeClassifier()
model_3.fit(X_train,Y_train)
pred_3 = model_3.predict(x_test)
cr3    = classification_report(y_test,pred_3)
print(cr3)

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1039
           1       0.93      0.92      0.92      1041

    accuracy                           0.92      2080
   macro avg       0.92      0.92      0.92      2080
weighted avg       0.92      0.92      0.92      2080



**4. Random Forest**

In [23]:
model_4 = RandomForestClassifier()
model_4.fit(X_train,Y_train)
pred_4 = model_4.predict(x_test)
cr4    = classification_report(y_test,pred_4)
print(cr4)

              precision    recall  f1-score   support

           0       0.97      0.87      0.92      1039
           1       0.88      0.97      0.92      1041

    accuracy                           0.92      2080
   macro avg       0.92      0.92      0.92      2080
weighted avg       0.92      0.92      0.92      2080



**5. XGBOOST**

In [24]:
model_5 = XGBClassifier()
model_5.fit(X_train,Y_train)
pred_5 = model_5.predict(x_test)
cr5    = classification_report(y_test,pred_5)
print(cr5)

              precision    recall  f1-score   support

           0       0.99      0.97      0.98      1039
           1       0.97      0.99      0.98      1041

    accuracy                           0.98      2080
   macro avg       0.98      0.98      0.98      2080
weighted avg       0.98      0.98      0.98      2080



**6.Catboost**

In [25]:
model_6 = CatBoostClassifier(iterations=200)
model_6.fit(X_train,Y_train)
pred_6 = model_5.predict(x_test)
cr6    = classification_report(y_test,pred_5)
print(cr6)

Learning rate set to 0.150531
0:	learn: 0.5821401	total: 181ms	remaining: 36s
1:	learn: 0.5013769	total: 196ms	remaining: 19.4s
2:	learn: 0.4525489	total: 218ms	remaining: 14.3s
3:	learn: 0.4163540	total: 234ms	remaining: 11.5s
4:	learn: 0.3876788	total: 251ms	remaining: 9.78s
5:	learn: 0.3702749	total: 267ms	remaining: 8.62s
6:	learn: 0.3580475	total: 282ms	remaining: 7.78s
7:	learn: 0.3414499	total: 300ms	remaining: 7.2s
8:	learn: 0.3242663	total: 319ms	remaining: 6.77s
9:	learn: 0.3162929	total: 335ms	remaining: 6.37s
10:	learn: 0.3081367	total: 350ms	remaining: 6.02s
11:	learn: 0.3006554	total: 366ms	remaining: 5.74s
12:	learn: 0.2964101	total: 381ms	remaining: 5.48s
13:	learn: 0.2922909	total: 397ms	remaining: 5.27s
14:	learn: 0.2867815	total: 412ms	remaining: 5.09s
15:	learn: 0.2822342	total: 428ms	remaining: 4.92s
16:	learn: 0.2774739	total: 443ms	remaining: 4.77s
17:	learn: 0.2732895	total: 458ms	remaining: 4.63s
18:	learn: 0.2703297	total: 473ms	remaining: 4.5s
19:	learn: 0.26

165:	learn: 0.0743445	total: 3.22s	remaining: 660ms
166:	learn: 0.0740407	total: 3.24s	remaining: 641ms
167:	learn: 0.0738952	total: 3.26s	remaining: 621ms
168:	learn: 0.0736111	total: 3.28s	remaining: 601ms
169:	learn: 0.0732068	total: 3.3s	remaining: 582ms
170:	learn: 0.0724000	total: 3.32s	remaining: 562ms
171:	learn: 0.0719623	total: 3.33s	remaining: 543ms
172:	learn: 0.0718325	total: 3.35s	remaining: 523ms
173:	learn: 0.0717010	total: 3.37s	remaining: 503ms
174:	learn: 0.0713374	total: 3.38s	remaining: 483ms
175:	learn: 0.0710057	total: 3.4s	remaining: 464ms
176:	learn: 0.0706008	total: 3.42s	remaining: 444ms
177:	learn: 0.0699425	total: 3.43s	remaining: 424ms
178:	learn: 0.0697495	total: 3.45s	remaining: 405ms
179:	learn: 0.0695976	total: 3.46s	remaining: 385ms
180:	learn: 0.0692061	total: 3.48s	remaining: 366ms
181:	learn: 0.0682318	total: 3.5s	remaining: 346ms
182:	learn: 0.0679932	total: 3.51s	remaining: 326ms
183:	learn: 0.0673562	total: 3.53s	remaining: 307ms
184:	learn: 0.0

**7. LSTM**

**In this model, 1.) The value for embedding feature vectors = 40 which are target feature vectors for the embedding layer. 2.) Single LSTM Layer with 100 nodes are used. 3.)Dense Layer with 1 neuron and sigmoid activation function is used since, this is a binary classification problem. 4) Dropout technique is used to avoid overfiiting and adam optimizer is used for optimizing the loss function.**

In [26]:
# Creating the LSTM Model for prediction
embedding_feature_vector = 40
model = Sequential()
model.add(Embedding(vocab_size,embedding_feature_vector,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [27]:
# Training the model
model.fit(X_train,Y_train,validation_data=(x_valid,y_valid),epochs=10,batch_size=64)

Epoch 1/10
264/264 [==============================] - 16s 49ms/step - loss: 0.2167 - accuracy: 0.9052 - val_loss: 0.0413 - val_accuracy: 0.9861
Epoch 2/10
264/264 [==============================] - 16s 59ms/step - loss: 0.0289 - accuracy: 0.9920 - val_loss: 0.0215 - val_accuracy: 0.9941
Epoch 3/10
264/264 [==============================] - 14s 52ms/step - loss: 0.0141 - accuracy: 0.9960 - val_loss: 0.0368 - val_accuracy: 0.9872
Epoch 4/10
264/264 [==============================] - 11s 41ms/step - loss: 0.0076 - accuracy: 0.9977 - val_loss: 0.0247 - val_accuracy: 0.9920
Epoch 5/10
264/264 [==============================] - 9s 34ms/step - loss: 0.0055 - accuracy: 0.9986 - val_loss: 0.0278 - val_accuracy: 0.9920
Epoch 6/10
264/264 [==============================] - 9s 35ms/step - loss: 0.0027 - accuracy: 0.9993 - val_loss: 0.0609 - val_accuracy: 0.9840
Epoch 7/10
264/264 [==============================] - 10s 38ms/step - loss: 0.0015 - accuracy: 0.9997 - val_loss: 0.0483 - val_accuracy: 0

In [28]:
predictions = model.predict(x_test)
binary_predictions = (predictions > 0.5).astype(int)
cr = classification_report(y_test,binary_predictions)
print(cr)

65/65 [==============================] - 1s 7ms/step
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      1039
           1       0.99      0.99      0.99      1041

    accuracy                           0.99      2080
   macro avg       0.99      0.99      0.99      2080
weighted avg       0.99      0.99      0.99      2080



# Evaluation of Models

**Tabulating the results of various implemented models.**

In [29]:
score_1 = accuracy_score(y_test,pred_1)
score_2 = accuracy_score(y_test,pred_2)
score_3 = accuracy_score(y_test,pred_3)
score_4 = accuracy_score(y_test,pred_4)
score_5 = accuracy_score(y_test,pred_5)
score_6 = accuracy_score(y_test,pred_6)
score_7 = accuracy_score(y_test,binary_predictions)
results = pd.DataFrame([["Logistic Regression",score_1],["Naive Bayes",score_2],["Decision Tree",score_3],
                       ["Random Forest",score_4],["XGBOOST",score_5],["CatBoost",score_6],["LSTM",score_7]],columns=["Model","Accuracy"])
results

Model  Accuracy
0  Logistic Regression  0.699038
1          Naive Bayes  0.707212
2        Decision Tree  0.924038
3        Random Forest  0.920192
4              XGBOOST  0.980288
5             CatBoost  0.980288
6                 LSTM  0.991827

**Discussion: From the above results, it appears that LSTM Model gives the highest accuracy amongst various models. Therefore, it is selected as the final model for making predictions on final testing data.**

**Predictions on Testing Data**

In [36]:
# Making Predictions on test data
predictions_test = pd.DataFrame(model.predict(x_test_final))
test_id = pd.DataFrame(test["id"])
submission = pd.concat([test_id,predictions_test],axis=1)
submission.columns = ["id","label"]
import numpy as np
threshold = 0.5


163/163 [==============================] - 1s 6ms/step


In [37]:
submission.head()

id         label
0  20800  6.357431e-05
1  20801  9.999975e-01
2  20802  9.999968e-01
3  20803  4.833606e-07
4  20804  9.999893e-01

In [38]:
import pandas as pd
# Define a threshold
threshold = 0.5

# Convert 'label' column to binary using the threshold
submission['label'] = submission['label'].apply(lambda x: 1 if x >= threshold else 0)

# Print the resulting DataFrame
submission.head()



id  label
0  20800      0
1  20801      1
2  20802      1
3  20803      0
4  20804      1